version: '3.1'
services:
  web_cam:
    image: odoo:16.0
    restart: always
    environment:
      - HOST=db15_cam
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      - db15_cam
    ports:
      - "8269:8069"
      - "8271:8071"
      - "8272:8072"
    volumes:
      - odoo-web-data-cam:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./backups:/mnt/backups
      - ./enterprise:/mnt/enterprise
    networks:
      - odoo_cam
    #command: odoo-bin --db_host db15_portillo --db_user odoo --db_password odoo --db_name odoo --db_port 5432 --xmlrpc_port 8069 --addons-path /mnt/extra-addons,/mnt/enterprise

  db15_cam:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-cam:/var/lib/postgresql/data/pgdata
    networks:
      - odoo_cam


volumes:
  odoo-web-data-cam:
  odoo-db-data-cam:

networks:
    odoo_cam: